export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TRANSFER_WAREHOUSE_SAME: "TRANSFER_WAREHOUSE_SAME",
  TRANSFER_INSUFFICIENT_STOCK: "TRANSFER_INSUFFICIENT_STOCK",
  TRANSFER_BATCH_IN_TRANSIT: "TRANSFER_BATCH_IN_TRANSIT",
  TRANSFER_ORDER_NOT_FOUND: "TRANSFER_ORDER_NOT_FOUND",
  TRANSFER_STATUS_CONFLICT: "TRANSFER_STATUS_CONFLICT",
  TRANSFER_FROZEN_CHANGED: "TRANSFER_FROZEN_CHANGED"
} as const;
