export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TRANSFER_INSUFFICIENT_STOCK: "TRANSFER_INSUFFICIENT_STOCK",
  TRANSFER_BATCH_ALREADY_IN_TRANSIT: "TRANSFER_BATCH_ALREADY_IN_TRANSIT",
  TRANSFER_FROZEN_CHANGED: "TRANSFER_FROZEN_CHANGED",
  TRANSFER_SOURCE_QUANTITY_CHANGED: "TRANSFER_SOURCE_QUANTITY_CHANGED",
  TRANSFER_SAME_WAREHOUSE: "TRANSFER_SAME_WAREHOUSE",
  TRANSFER_LINES_EMPTY: "TRANSFER_LINES_EMPTY",
  TRANSFER_QUANTITY_INVALID: "TRANSFER_QUANTITY_INVALID",
  TRANSFER_ORDER_NOT_FOUND: "TRANSFER_ORDER_NOT_FOUND",
  TRANSFER_ORDER_NOT_IN_TRANSIT: "TRANSFER_ORDER_NOT_IN_TRANSIT"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
